server:
  port: 8081
spring:
  application:
    name: log-consumer
  kafka:
    bootstrap-servers: localhost:9092
    streams:
      application-id: log-consumer-app
management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true